apiVersion: v1
kind: Service
metadata:
  name: qrcodegenerator-v0102
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: qrcodegenerator-v0102
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcodegenerator-v0102
spec:
  selector:
    matchLabels:
      app: qrcodegenerator-v0102
  replicas: 1
  template:
    metadata:
      labels:
        app: qrcodegenerator-v0102
    spec:
      containers:
      - name: qrcodegenerator-v0102
        image: asia.gcr.io/amala-stg/qrcodegenerator:v1.2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: spring-active-profiles
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: qrcodegenerator-v0102
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /amala/v1.2/qrcodegenerator
            backend:
              serviceName: qrcodegenerator-v0102
              servicePort: 80